default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 12345
  host: localhost

development:
  <<: *default
  database: BordadosFEI_development

test:
  <<: *default
  database: BordadosFEI_test

production:
  <<: *default
  database: BordadosFEI_production
  username: BordadosFEI
  password: <%= ENV['BORDADOSFEI_DATABASE_PASSWORD'] %>
