# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa9dab3b6f631f04dcf5fbd09b64747f401ead6825b43faae290b4cbdbc7420894c335ff125d2c9c1df4df3e1b0bdd8d851f076cec315c476aaafbe50360ab5

test:
  secret_key_base: 3d2196893aad79379883e97e29542e2c4b0b2f50699f0d56f0f4233ccbf661697017e110404049fb1ebc35c0339872ccf91307270ef39d99ce0d7bd377874c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
