# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b403dcb8a114dd12b0735e608099c9e7f5825930dbfce43427fb0248ae8fa993e679905f80f1f0d1ab85acd20da2b5a7deb3c3fc752cd4a843174ed12c349754

test:
  secret_key_base: ae4e81bc10a13aa0a002524e6ce123de9b25bbfcc27b6d9133f0b754f2c423f4c2904acfcb805aa56aa1ef65d42598a435a71775e272c6aff58f1925c712043c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
